variables:
  CODECOV_TOKEN: "8ff529cc-45e2-4835-8485-29df0961b10b"
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git libgsl0-dev libv8-dev"

image: rocker/tidyverse

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc texlive-xetex
  - apt-get install -y --no-install-recommends ${APT_PKGS}
  - R -e 'install.packages(c("data.tree", "dplyr", "DiagrammeR", "glue", "purrr", "yum"))'
  - R -e 'install.packages(c("knitr", "markdown", "rmarkdown", "devtools", "covr", "testthat", "here", "rENA"))'
  - R -e 'install.packages("tinytex");'
  - R -e 'install.packages(c("DiagrammeRsvg", "googlesheets4", "textreadr"))'
  - R -e 'install.packages(c("openxlsx", "XLConnect", "readxl", "writexl"))'
  - R -e 'devtools::install_gitlab("r-packages/yum")'
  - R -e 'devtools::install_gitlab("r-packages/justifier")'
  - R -e 'devtools::install_gitlab("r-packages/preregr")'
  - apt-get install -y lmodern texlive-fonts-recommended
  #- R -e 'tinytex::tlmgr_update(); tinytex::tlmgr_install("lmodern");'

devtools-check:
  stage: test
  script:
    - R -e 'devtools::check()'

pages:
  stage: build
  script:
    - mkdir public/iROCK
    - cp -R iROCK public
    - mkdir public/img
    - cp img/hex-logo.png public/img/hex-logo.png
  artifacts:
    paths:
      - public
  only:
    - prod

coverage:
  stage: deploy
  allow_failure: true
  when: on_success
  script:
    - install2.r covr
    - R -e 'install.packages(c("data.tree", "dplyr", "DiagrammeR", "glue", "purrr", "yum"))'
    - R -e 'install.packages(c("knitr", "rmarkdown", "devtools", "covr", "testthat", "here", "rENA"))'
    - R -e 'install.packages("tinytex")'
    - R -e 'install.packages("DiagrammeRsvg")'
    - R -e 'devtools::install_gitlab("r-packages/yum")'
    - R -e 'devtools::install_gitlab("r-packages/justifier")'
    - R -e 'devtools::install()'
    - R -e 'covr::codecov(type = c("tests", "examples"), quiet = FALSE)'
  only:
    - prod
