variables:
  CODECOV_TOKEN: "8ff529cc-45e2-4835-8485-29df0961b10b"
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git"

pages:
  stage: build
  image: alpine:latest
  script:
    - mkdir public/iROCK
    - cp -R iROCK public/iROCK
  artifacts:
    paths:
    - public
  only:
  - master

devtools-check:
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends ${APT_PKGS}
    - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
  stage: test
  image: rocker/tidyverse
  script:
    - R -e 'install.packages(c("data.tree", "dplyr", "DiagrammeR", "glue", "purrr"))'
    - R -e 'install.packages(c("knitr", "rmarkdown", "covr", "testthat"))'
    - R -e 'devtools::install_gitlab("r-packages/yum")'
    - R -e 'devtools::install_gitlab("r-packages/ufs")'
    - R -e 'devtools::check()'
  tags:
    - docker

coverage:
  stage: deploy
  tags:
    - docker
  image: rocker/tidyverse
  when: on_success
  only:
    - master
  script:
    - install2.r covr
    - R -e 'install.packages(c("data.tree", "dplyr", "DiagrammeR", "glue", "purrr"))'
    - R -e 'install.packages(c("devtools", "covr", "testthat", "here"))'
    - R -e 'devtools::install_gitlab("r-packages/yum")'
    - R -e 'devtools::install_gitlab("r-packages/ufs")'
    - R -e 'devtools::install()'
    - R -e 'covr::codecov(type = c("tests", "examples"), quiet = FALSE)'
